[versions]
flixelgdx = "0.6.0"
graalvm = "24.2.0"
jetbrainsAnnotations = "26.1.0"
jna = "5.17.0"
spotless = "8.6.0"
teavm = "0.15.0"
vanniktech = "0.33.0"
vlc = "3.0.23"

[libraries]
flixelgdx-core = { module = "org.flixelgdx:flixelgdx-core", version.ref = "flixelgdx" }
flixelgdx-desktop = { module = "org.flixelgdx:flixelgdx-desktop", version.ref = "flixelgdx" }
flixelgdx-html5 = { module = "org.flixelgdx:flixelgdx-html5", version.ref = "flixelgdx" }
graalvm-nativeimage = { module = "org.graalvm.sdk:nativeimage", version.ref = "graalvm" }
jetbrains-annotations = { module = "org.jetbrains:annotations", version.ref = "jetbrainsAnnotations" }
jna = { module = "net.java.dev.jna:jna", version.ref = "jna" }

[plugins]
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
teavm = { id = "org.teavm", version.ref = "teavm" }
vanniktech = { id = "com.vanniktech.maven.publish", version.ref = "vanniktech" }
